import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import { Inter, Playfair_Display } from 'next/font/google'

import { ThemeProvider } from '@/components/theme-provider'
import { Toaster } from '@/components/ui/sonner'
import { cn } from '@/lib/utils'

import { Header } from '@/components/header'
import { Footer } from '@/components/footer'

import '@/style/globals.css'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})
const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})
const inter = Inter({ subsets: ['latin'], variable: '--font-sans' })
const playfair = Playfair_Display({
	subsets: ['latin'],
	variable: '--font-serif',
})

export const metadata: Metadata = {
	title: 'MindMate',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en" suppressHydrationWarning className="scroll-smooth">
			<body
				className={cn(
					'flex min-h-screen flex-col container mx-auto px-7',
					geistSans.variable,
					geistMono.variable,
					inter.variable,
					playfair.variable
				)}
			>
				<ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
					<Header />
					<main className="grow">{children}</main>
					<Toaster />
					<Footer />
				</ThemeProvider>
			</body>
		</html>
	)
}
